apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager-db
  labels:
    app: task-manager-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager-db
  template:
    metadata:
      labels:
        app: task-manager-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: cicd-task-db   # Replace with your actual DB name
        - name: POSTGRES_USER
          value: postgres          # Replace with your DB username
        - name: POSTGRES_PASSWORD
          value: prodpass      # Replace with your DB password
        ports:
        - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager-db-service   # This acts as the internal domain name!
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: task-manager-db